- name: Retrieve the public key contents
  become: "yes"
  shell: "cat {{ key_location }}"
  register: pubk
  args:
    executable: /bin/bash

- name: Create a key pair in nab git
  become: "yes"
  uri:
    url: https://api.github.com/api/v3/user/keys
    method: POST
    user: P733287
    password: "{{ git_password }}"
    body: '{"title":"{{ key_title }}","key":"{{ pubk.stdout }}"}'
    force_basic_auth: yes
    body_format: json
    status_code: 201