---
- name: Provision another Phoenix Server
  hosts: localhost
  vars:
    random_num: "{{ 100 | random }}"

  tasks:
    - name: Do Task
      
    - name: Do another task

- name: do more plays
  hosts: localhost
  tasks:
  - name: Ping check
    ping:
    become: true

- name: Run role tasks
  hosts: localhost
  roles:
    - role-template